# Generated by Django 4.2.7 on 2026-06-25 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('headline', models.CharField(help_text='Short tagline, e.g. "Swing trader · FX & indices".', max_length=160)),
                ('strategy', models.TextField(help_text="Demo description of the trader's approach.")),
                ('win_rate', models.DecimalField(decimal_places=1, default=0, help_text='Demo win rate %, e.g. 68.5.', max_digits=5)),
                ('return_pct', models.DecimalField(decimal_places=1, default=0, help_text='Demo 30-day return %, e.g. 14.2.', max_digits=6)),
                ('followers', models.PositiveIntegerField(default=0, help_text='Demo follower count (illustrative).')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('markets', models.CharField(help_text='Markets traded, e.g. "Forex, Indices".', max_length=120)),
                ('accent', models.CharField(choices=[('emerald', 'Emerald'), ('teal', 'Teal'), ('blue', 'Blue'), ('violet', 'Violet'), ('amber', 'Amber')], default='emerald', help_text='Avatar accent colour for the initials circle.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Master Trader (Demo)',
                'verbose_name_plural': 'Master Traders (Demo)',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CopyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_demo_amount', models.DecimalField(decimal_places=2, default=0, help_text='Simulated demo allocation. Not a real balance transfer.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='copytrading.mastertrader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Copy Relationship (Demo)',
                'verbose_name_plural': 'Copy Relationships (Demo)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='copyrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'master'), name='unique_active_copy_per_user_master'),
        ),
    ]
