# Generated by Django 4.2.7 on 2026-06-28 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copyrelationship',
            options={'ordering': ['-created_at'], 'verbose_name': 'Copy Relationship', 'verbose_name_plural': 'Copy Relationships'},
        ),
        migrations.AlterModelOptions(
            name='mastertrader',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Master Trader', 'verbose_name_plural': 'Master Traders'},
        ),
        migrations.AlterField(
            model_name='copyrelationship',
            name='allocated_demo_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Allocation amount.', max_digits=12, verbose_name='Allocation'),
        ),
        migrations.AlterField(
            model_name='mastertrader',
            name='followers',
            field=models.PositiveIntegerField(default=0, help_text='Follower count.'),
        ),
        migrations.AlterField(
            model_name='mastertrader',
            name='return_pct',
            field=models.DecimalField(decimal_places=1, default=0, help_text='30-day return %, e.g. 14.2.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='mastertrader',
            name='strategy',
            field=models.TextField(help_text="Description of the trader's approach."),
        ),
        migrations.AlterField(
            model_name='mastertrader',
            name='win_rate',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Win rate %, e.g. 68.5.', max_digits=5),
        ),
        migrations.CreateModel(
            name='MasterTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_currency', models.CharField(help_text='e.g. Bitcoin', max_length=120)),
                ('crypto_symbol', models.CharField(help_text='e.g. BTC/USD', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('direction', models.CharField(choices=[('rise', 'Rise'), ('fall', 'Fall')], default='rise', max_length=4)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], default='pending', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by an admin — the trade has been checked and meets standards.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='copytrading.mastertrader')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-opened_at'],
            },
        ),
    ]
