# Generated by Django 4.2.7 on 2025-10-31 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken_loginhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='btc_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bitcoin Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_on_expiration',
            field=models.BooleanField(default=True, help_text='Receive email on plan expiration'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_on_roi',
            field=models.BooleanField(default=True, help_text='Receive email on ROI/profit credits'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_on_withdrawal',
            field=models.BooleanField(default=True, help_text='Receive email on withdrawal requests'),
        ),
        migrations.AddField(
            model_name='user',
            name='eth_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ethereum Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='ltc_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Litecoin Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='swift_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='usdt_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='USDT Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('profit', 'Profit'), ('bonus', 'Bonus'), ('referral', 'Referral'), ('system', 'System'), ('security', 'Security')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
