# Generated by Django 4.2.7 on 2026-06-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_account_name_user_account_number_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='btc_balance',
            field=models.DecimalField(decimal_places=8, default=0, help_text="User's BTC balance (from USD<->BTC swaps)", max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, help_text='Hashed transaction PIN for authorising transfers', max_length=128),
        ),
    ]
