# Generated by Django 4.2.7 on 2026-06-27 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_logincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='created_by_admin',
            field=models.BooleanField(default=False, help_text='Generated by an admin as an email fallback.'),
        ),
        migrations.AddField(
            model_name='logincode',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='The admin who generated this code (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_login_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logincode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate this code so it can no longer be used to log in.'),
        ),
        migrations.AlterField(
            model_name='logincode',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='logincode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
