# Generated by Django 4.2.7 on 2026-06-27 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_logincode_created_by_admin_logincode_generated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_access_unlocked',
            field=models.BooleanField(default=False, help_text='Whether this user has entered a valid platform access code.'),
        ),
        migrations.AddField(
            model_name='user',
            name='course_access_unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The access code users type to unlock the platform (case-insensitive).', max_length=32, unique=True)),
                ('label', models.CharField(blank=True, help_text='Optional note, e.g. "Launch cohort" or "Q3 promo".', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Only active codes can be redeemed. Uncheck to retire a code.')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Code',
                'verbose_name_plural': 'Access Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
