# Generated by Django 4.2.7 on 2026-06-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_summit26_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course_access_unlocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course_access_unlocked_at',
        ),
        migrations.DeleteModel(
            name='AccessCode',
        ),
    ]
