# Generated by Django 4.2.7 on 2026-06-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_kycverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Email two-factor authentication — a code is emailed at each sign-in.'),
        ),
    ]
