# Generated by Django 4.2.7 on 2026-06-25 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('symbol', models.CharField(help_text='e.g. EURUSD, BTCUSD, AAPL', max_length=20)),
                ('market', models.CharField(choices=[('forex', 'Forex'), ('crypto', 'Crypto'), ('stocks', 'Stocks'), ('indices', 'Indices'), ('commodities', 'Commodities')], default='forex', max_length=20)),
                ('bias', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('timeframe', models.CharField(help_text='e.g. 4H, 1D', max_length=20)),
                ('body', models.TextField()),
                ('tv_symbol', models.CharField(blank=True, help_text='TradingView symbol for the mini widget, e.g. FX:EURUSD', max_length=50)),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='analysis/')),
                ('status', models.CharField(choices=[('published', 'Published'), ('pending', 'Pending review'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('is_house', models.BooleanField(default=False, help_text='Admin/seeded "market biases & flow" content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='Null means an admin/house post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
