# Generated by Django 4.2.7 on 2026-06-25 20:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_name', models.CharField(blank=True, max_length=160)),
                ('buyer_phone', models.CharField(blank=True, max_length=40)),
                ('buyer_country', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('payment_method', models.CharField(blank=True, help_text='e.g. USDT, Bitcoin', max_length=60)),
                ('tx_reference', models.CharField(blank=True, help_text='On-chain tx hash / reference', max_length=255)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='course_purchases/')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='education.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course purchase',
                'verbose_name_plural': 'Course purchases',
                'ordering': ['-created_at'],
            },
        ),
    ]
