"""End-to-end tests for the passwordless login-code system, with a focus on the
admin-generated fallback code flow (generate → user logs in → admin deactivate)."""

from datetime import timedelta

from django.contrib.auth import get_user_model
from django.test import TestCase, override_settings
from django.urls import reverse
from django.utils import timezone

from accounts.models import LoginCode, AccessCode

User = get_user_model()

# The project uses a manifest static storage in production; under test there is
# no collected manifest, so fall back to plain static storage for template renders.
_TEST_STATIC = override_settings(
    STATICFILES_STORAGE='django.contrib.staticfiles.storage.StaticFilesStorage'
)


@_TEST_STATIC
class LoginCodeModelTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username='buyer', email='buyer@example.com', password='x'
        )

    def test_code_and_expiry_autogenerated(self):
        lc = LoginCode.objects.create(user=self.user)
        self.assertEqual(len(lc.code), 6)
        self.assertTrue(lc.code.isdigit())
        self.assertIsNotNone(lc.expires_at)

    def test_user_vs_admin_expiry_window(self):
        user_code = LoginCode.objects.create(user=self.user)
        admin_code = LoginCode.objects.create(user=self.user, created_by_admin=True)
        user_minutes = (user_code.expires_at - user_code.created_at).total_seconds() / 60
        admin_minutes = (admin_code.expires_at - admin_code.created_at).total_seconds() / 60
        self.assertAlmostEqual(user_minutes, LoginCode.USER_EXPIRY_MINUTES, delta=1)
        self.assertAlmostEqual(admin_minutes, LoginCode.ADMIN_EXPIRY_MINUTES, delta=1)

    def test_is_valid_lifecycle(self):
        lc = LoginCode.objects.create(user=self.user, created_by_admin=True)
        self.assertTrue(lc.is_valid())
        self.assertEqual(lc.status, 'Active')

        lc.deactivate()
        self.assertFalse(lc.is_valid())
        self.assertEqual(lc.status, 'Deactivated')

        lc.is_active = True
        lc.is_used = True
        lc.save()
        self.assertFalse(lc.is_valid())
        self.assertEqual(lc.status, 'Used')

    def test_expired_code_invalid(self):
        lc = LoginCode.objects.create(user=self.user)
        lc.expires_at = timezone.now() - timedelta(minutes=1)
        lc.save()
        self.assertFalse(lc.is_valid())
        self.assertEqual(lc.status, 'Expired')


@_TEST_STATIC
class LoginCodeVerifyFlowTests(TestCase):
    """The fallback flow: a user given a code out-of-band signs in by going
    straight to the verify page (no prior email-request step / session)."""

    def setUp(self):
        self.user = User.objects.create_user(
            username='buyer', email='buyer@example.com', password='x'
        )
        self.verify_url = reverse('accounts:login_code_verify')

    def _make_admin_code(self):
        return LoginCode.objects.create(user=self.user, created_by_admin=True)

    def test_login_with_admin_code(self):
        lc = self._make_admin_code()
        resp = self.client.post(
            self.verify_url,
            {'email': 'buyer@example.com', 'code': lc.code},
        )
        self.assertEqual(resp.status_code, 302)
        self.assertIn('_auth_user_id', self.client.session)
        self.assertEqual(int(self.client.session['_auth_user_id']), self.user.pk)
        lc.refresh_from_db()
        self.assertTrue(lc.is_used)

    def test_deactivated_code_rejected(self):
        lc = self._make_admin_code()
        lc.deactivate()
        resp = self.client.post(
            self.verify_url,
            {'email': 'buyer@example.com', 'code': lc.code},
        )
        self.assertEqual(resp.status_code, 200)
        self.assertNotIn('_auth_user_id', self.client.session)
        lc.refresh_from_db()
        self.assertFalse(lc.is_used)  # rejected code is not consumed

    def test_expired_code_rejected(self):
        lc = self._make_admin_code()
        lc.expires_at = timezone.now() - timedelta(minutes=1)
        lc.save()
        resp = self.client.post(
            self.verify_url,
            {'email': 'buyer@example.com', 'code': lc.code},
        )
        self.assertNotIn('_auth_user_id', self.client.session)

    def test_wrong_code_rejected(self):
        self._make_admin_code()
        resp = self.client.post(
            self.verify_url,
            {'email': 'buyer@example.com', 'code': '000000'},
        )
        self.assertNotIn('_auth_user_id', self.client.session)

    def test_code_single_use(self):
        lc = self._make_admin_code()
        self.client.post(self.verify_url, {'email': 'buyer@example.com', 'code': lc.code})
        self.assertIn('_auth_user_id', self.client.session)
        # second attempt with the same (now used) code must fail
        self.client.logout()
        resp = self.client.post(
            self.verify_url, {'email': 'buyer@example.com', 'code': lc.code}
        )
        self.assertNotIn('_auth_user_id', self.client.session)


@_TEST_STATIC
class LoginCodeAdminTests(TestCase):
    """The admin generates and revokes codes from the Django admin site."""

    def setUp(self):
        self.admin = User.objects.create_superuser(
            username='root', email='root@example.com', password='adminpass'
        )
        self.user = User.objects.create_user(
            username='buyer', email='buyer@example.com', password='x'
        )
        self.client.force_login(self.admin)

    def test_admin_generates_code_for_user(self):
        add_url = reverse('admin:accounts_logincode_add')
        resp = self.client.post(add_url, {'user': self.user.pk}, follow=True)
        self.assertEqual(resp.status_code, 200)
        lc = LoginCode.objects.get(user=self.user)
        self.assertEqual(len(lc.code), 6)
        self.assertTrue(lc.created_by_admin)
        self.assertEqual(lc.generated_by, self.admin)
        self.assertTrue(lc.is_active)
        self.assertTrue(lc.is_valid())

    def test_admin_deactivate_action(self):
        lc = LoginCode.objects.create(user=self.user, created_by_admin=True)
        changelist = reverse('admin:accounts_logincode_changelist')
        resp = self.client.post(
            changelist,
            {'action': 'deactivate_codes', '_selected_action': [str(lc.pk)]},
            follow=True,
        )
        self.assertEqual(resp.status_code, 200)
        lc.refresh_from_db()
        self.assertFalse(lc.is_active)
        self.assertFalse(lc.is_valid())

    def test_admin_generated_code_then_user_logs_in(self):
        # full fallback path: admin mints a code, user signs in with it
        add_url = reverse('admin:accounts_logincode_add')
        self.client.post(add_url, {'user': self.user.pk})
        lc = LoginCode.objects.get(user=self.user)

        guest = self.client.__class__()  # fresh client (no admin session)
        resp = guest.post(
            reverse('accounts:login_code_verify'),
            {'email': 'buyer@example.com', 'code': lc.code},
        )
        self.assertEqual(resp.status_code, 302)
        self.assertIn('_auth_user_id', guest.session)


@_TEST_STATIC
class AccessCodeModelTests(TestCase):
    def test_code_normalised_uppercase(self):
        ac = AccessCode.objects.create(code='  launch99 ')
        self.assertEqual(ac.code, 'LAUNCH99')

    def test_match_is_case_insensitive_and_active_only(self):
        # SUMMIT26 is seeded by migration 0008
        self.assertIsNotNone(AccessCode.match('summit26'))
        self.assertIsNotNone(AccessCode.match('  SuMMit26 '))
        self.assertIsNone(AccessCode.match('nope'))

        AccessCode.objects.create(code='OLD2025', is_active=False)
        self.assertIsNone(AccessCode.match('old2025'))


@_TEST_STATIC
class AccessGateTests(TestCase):
    EDU_PATH = '/education/'
    BUY_PATH = '/buy/'

    def setUp(self):
        # SUMMIT26 is seeded by migration 0008; reuse it.
        self.code, _ = AccessCode.objects.get_or_create(
            code='SUMMIT26', defaults={'is_active': True}
        )
        self.code.is_active = True
        self.code.times_used = 0
        self.code.save()
        self.user = User.objects.create_user(
            username='member', email='member@example.com', password='pw'
        )
        self.gate_url = reverse('accounts:access_gate')

    # --- middleware gating ---
    def test_locked_user_redirected_to_gate_from_courses(self):
        self.client.force_login(self.user)
        resp = self.client.get(self.EDU_PATH)
        self.assertEqual(resp.status_code, 302)
        self.assertIn(self.gate_url, resp.url)

    def test_locked_user_redirected_to_gate_from_store(self):
        self.client.force_login(self.user)
        resp = self.client.get(self.BUY_PATH)
        self.assertEqual(resp.status_code, 302)
        self.assertIn(self.gate_url, resp.url)

    def test_anonymous_redirected_to_login(self):
        resp = self.client.get(self.EDU_PATH)
        self.assertEqual(resp.status_code, 302)
        self.assertIn('/auth/login/', resp.url)

    def test_staff_bypasses_gate(self):
        self.user.is_staff = True
        self.user.save(update_fields=['is_staff'])
        self.client.force_login(self.user)
        resp = self.client.get(self.EDU_PATH)
        self.assertNotEqual(resp.status_code, 302)

    def test_unlocked_user_passes(self):
        self.user.grant_course_access()
        self.client.force_login(self.user)
        resp = self.client.get(self.EDU_PATH)
        self.assertEqual(resp.status_code, 200)

    # --- gate view redemption ---
    def test_correct_code_unlocks_permanently_and_redirects_next(self):
        self.client.force_login(self.user)
        resp = self.client.post(
            self.gate_url, {'access_code': 'summit26', 'next': self.EDU_PATH}
        )
        self.assertEqual(resp.status_code, 302)
        self.assertEqual(resp.url, self.EDU_PATH)
        self.user.refresh_from_db()
        self.assertTrue(self.user.course_access_unlocked)
        self.assertIsNotNone(self.user.course_access_unlocked_at)
        self.code.refresh_from_db()
        self.assertEqual(self.code.times_used, 1)

    def test_wrong_code_does_not_unlock(self):
        self.client.force_login(self.user)
        resp = self.client.post(self.gate_url, {'access_code': 'WRONG'})
        self.assertEqual(resp.status_code, 200)
        self.user.refresh_from_db()
        self.assertFalse(self.user.course_access_unlocked)

    def test_inactive_code_does_not_unlock(self):
        self.code.is_active = False
        self.code.save(update_fields=['is_active'])
        self.client.force_login(self.user)
        resp = self.client.post(self.gate_url, {'access_code': 'SUMMIT26'})
        self.assertEqual(resp.status_code, 200)
        self.user.refresh_from_db()
        self.assertFalse(self.user.course_access_unlocked)

    def test_gate_rejects_open_redirect_next(self):
        self.client.force_login(self.user)
        resp = self.client.post(
            self.gate_url, {'access_code': 'SUMMIT26', 'next': 'https://evil.com/x'}
        )
        self.assertEqual(resp.status_code, 302)
        self.assertNotIn('evil.com', resp.url)
