"""End-to-end tests for the passwordless login-code system, with a focus on the
admin-generated fallback code flow (generate → user logs in → admin deactivate)."""

from datetime import timedelta

from django.contrib.auth import get_user_model
from django.test import TestCase, override_settings
from django.urls import reverse
from django.utils import timezone

from accounts.models import LoginCode

User = get_user_model()

# The project uses a manifest static storage in production; under test there is
# no collected manifest, so fall back to plain static storage for template renders.
_TEST_STATIC = override_settings(
    STATICFILES_STORAGE='django.contrib.staticfiles.storage.StaticFilesStorage'
)


@_TEST_STATIC
class LoginCodeModelTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username='buyer', email='buyer@example.com', password='x'
        )

    def test_code_and_expiry_autogenerated(self):
        lc = LoginCode.objects.create(user=self.user)
        self.assertEqual(len(lc.code), 6)
        self.assertTrue(lc.code.isdigit())
        self.assertIsNotNone(lc.expires_at)

    def test_user_vs_admin_expiry_window(self):
        user_code = LoginCode.objects.create(user=self.user)
        admin_code = LoginCode.objects.create(user=self.user, created_by_admin=True)
        user_minutes = (user_code.expires_at - user_code.created_at).total_seconds() / 60
        admin_minutes = (admin_code.expires_at - admin_code.created_at).total_seconds() / 60
        self.assertAlmostEqual(user_minutes, LoginCode.USER_EXPIRY_MINUTES, delta=1)
        self.assertAlmostEqual(admin_minutes, LoginCode.ADMIN_EXPIRY_MINUTES, delta=1)

    def test_is_valid_lifecycle(self):
        lc = LoginCode.objects.create(user=self.user, created_by_admin=True)
        self.assertTrue(lc.is_valid())
        self.assertEqual(lc.status, 'Active')

        lc.deactivate()
        self.assertFalse(lc.is_valid())
        self.assertEqual(lc.status, 'Deactivated')

        lc.is_active = True
        lc.is_used = True
        lc.save()
        self.assertFalse(lc.is_valid())
        self.assertEqual(lc.status, 'Used')

    def test_expired_code_invalid(self):
        lc = LoginCode.objects.create(user=self.user)
        lc.expires_at = timezone.now() - timedelta(minutes=1)
        lc.save()
        self.assertFalse(lc.is_valid())
        self.assertEqual(lc.status, 'Expired')


@_TEST_STATIC
class LoginCodeVerifyFlowTests(TestCase):
    """The fallback flow: a user given a code out-of-band signs in by going
    straight to the verify page (no prior email-request step / session)."""

    def setUp(self):
        self.user = User.objects.create_user(
            username='buyer', email='buyer@example.com', password='x'
        )
        self.verify_url = reverse('accounts:login_code_verify')

    def _make_admin_code(self):
        return LoginCode.objects.create(user=self.user, created_by_admin=True)

    def test_login_with_admin_code(self):
        lc = self._make_admin_code()
        resp = self.client.post(
            self.verify_url,
            {'email': 'buyer@example.com', 'code': lc.code},
        )
        self.assertEqual(resp.status_code, 302)
        self.assertIn('_auth_user_id', self.client.session)
        self.assertEqual(int(self.client.session['_auth_user_id']), self.user.pk)
        lc.refresh_from_db()
        self.assertTrue(lc.is_used)

    def test_deactivated_code_rejected(self):
        lc = self._make_admin_code()
        lc.deactivate()
        resp = self.client.post(
            self.verify_url,
            {'email': 'buyer@example.com', 'code': lc.code},
        )
        self.assertEqual(resp.status_code, 200)
        self.assertNotIn('_auth_user_id', self.client.session)
        lc.refresh_from_db()
        self.assertFalse(lc.is_used)  # rejected code is not consumed

    def test_expired_code_rejected(self):
        lc = self._make_admin_code()
        lc.expires_at = timezone.now() - timedelta(minutes=1)
        lc.save()
        resp = self.client.post(
            self.verify_url,
            {'email': 'buyer@example.com', 'code': lc.code},
        )
        self.assertNotIn('_auth_user_id', self.client.session)

    def test_wrong_code_rejected(self):
        self._make_admin_code()
        resp = self.client.post(
            self.verify_url,
            {'email': 'buyer@example.com', 'code': '000000'},
        )
        self.assertNotIn('_auth_user_id', self.client.session)

    def test_code_single_use(self):
        lc = self._make_admin_code()
        self.client.post(self.verify_url, {'email': 'buyer@example.com', 'code': lc.code})
        self.assertIn('_auth_user_id', self.client.session)
        # second attempt with the same (now used) code must fail
        self.client.logout()
        resp = self.client.post(
            self.verify_url, {'email': 'buyer@example.com', 'code': lc.code}
        )
        self.assertNotIn('_auth_user_id', self.client.session)


@_TEST_STATIC
class LoginCodeAdminTests(TestCase):
    """The admin generates and revokes codes from the Django admin site."""

    def setUp(self):
        self.admin = User.objects.create_superuser(
            username='root', email='root@example.com', password='adminpass'
        )
        self.user = User.objects.create_user(
            username='buyer', email='buyer@example.com', password='x'
        )
        self.client.force_login(self.admin)

    def test_admin_generates_code_for_user(self):
        add_url = reverse('admin:accounts_logincode_add')
        resp = self.client.post(add_url, {'user': self.user.pk}, follow=True)
        self.assertEqual(resp.status_code, 200)
        lc = LoginCode.objects.get(user=self.user)
        self.assertEqual(len(lc.code), 6)
        self.assertTrue(lc.created_by_admin)
        self.assertEqual(lc.generated_by, self.admin)
        self.assertTrue(lc.is_active)
        self.assertTrue(lc.is_valid())

    def test_admin_deactivate_action(self):
        lc = LoginCode.objects.create(user=self.user, created_by_admin=True)
        changelist = reverse('admin:accounts_logincode_changelist')
        resp = self.client.post(
            changelist,
            {'action': 'deactivate_codes', '_selected_action': [str(lc.pk)]},
            follow=True,
        )
        self.assertEqual(resp.status_code, 200)
        lc.refresh_from_db()
        self.assertFalse(lc.is_active)
        self.assertFalse(lc.is_valid())

    def test_admin_generated_code_then_user_logs_in(self):
        # full fallback path: admin mints a code, user signs in with it
        add_url = reverse('admin:accounts_logincode_add')
        self.client.post(add_url, {'user': self.user.pk})
        lc = LoginCode.objects.get(user=self.user)

        guest = self.client.__class__()  # fresh client (no admin session)
        resp = guest.post(
            reverse('accounts:login_code_verify'),
            {'email': 'buyer@example.com', 'code': lc.code},
        )
        self.assertEqual(resp.status_code, 302)
        self.assertIn('_auth_user_id', guest.session)



from io import BytesIO
from accounts.models import KYCVerification


def _png_bytes():
    from PIL import Image
    buf = BytesIO()
    Image.new('RGB', (4, 4), (120, 90, 200)).save(buf, 'PNG')
    return buf.getvalue()


@_TEST_STATIC
class KYCAndDepositTests(TestCase):
    def setUp(self):
        from unittest import mock
        p = mock.patch('accounts.email_utils.EmailService.send_email', return_value=True)
        p.start()
        self.addCleanup(p.stop)
        self.user = User.objects.create_user(
            username='kuser', email='kuser@example.com', password='pw', is_staff=False,
        )

    def _submit_kyc(self):
        from django.core.files.uploadedfile import SimpleUploadedFile
        doc = SimpleUploadedFile('id.png', _png_bytes(), content_type='image/png')
        selfie = SimpleUploadedFile('selfie.png', _png_bytes(), content_type='image/png')
        return self.client.post(reverse('dashboard:kyc'), {
            'first_name': 'Jane', 'last_name': 'Doe', 'gender': 'female',
            'country': 'Nigeria', 'city': 'Lagos', 'postal_code': '100001',
            'address_line_1': '1 Main St', 'document_type': 'passport',
            'document_image': doc, 'selfie_image': selfie,
            'info_correct': 'on', 'is_individual': 'on',
        })

    def test_user_not_verified_by_default(self):
        self.assertFalse(self.user.is_kyc_verified)
        self.assertIsNone(self.user.kyc_status)

    def test_deposit_blocked_until_verified(self):
        self.client.force_login(self.user)
        r = self.client.post(reverse('dashboard:new_deposit'), {'amount': '500'})
        self.assertEqual(r.status_code, 302)
        self.assertIn(reverse('dashboard:kyc'), r.url)

    def test_withdraw_blocked_until_verified(self):
        self.client.force_login(self.user)
        r = self.client.get(reverse('dashboard:withdraw_funds'))
        self.assertEqual(r.status_code, 302)
        self.assertIn(reverse('dashboard:kyc'), r.url)

    def test_kyc_submit_creates_pending(self):
        self.client.force_login(self.user)
        r = self._submit_kyc()
        self.assertEqual(r.status_code, 302)
        kyc = KYCVerification.objects.get(user=self.user)
        self.assertEqual(kyc.status, 'pending')
        self.assertEqual(kyc.first_name, 'Jane')
        self.user.refresh_from_db()
        self.assertEqual(self.user.first_name, 'Jane')  # synced to user
        self.assertFalse(self.user.is_kyc_verified)

    def test_admin_approve_unlocks_and_deposit_creates_pending(self):
        admin = User.objects.create_superuser('root2', 'root2@example.com', 'pw')
        self.client.force_login(self.user)
        self._submit_kyc()
        kyc = KYCVerification.objects.get(user=self.user)
        kyc.approve(by_user=admin)
        self.user.refresh_from_db()
        self.assertTrue(self.user.is_kyc_verified)

        # Now a deposit is allowed and creates a PENDING transaction (no balance credit)
        from django.core.files.uploadedfile import SimpleUploadedFile
        before = self.user.balance
        proof = SimpleUploadedFile('p.png', _png_bytes(), content_type='image/png')
        r = self.client.post(reverse('dashboard:new_deposit'), {
            'amount': '500', 'payment_method': 'USDT', 'proof_image': proof,
        })
        self.assertEqual(r.status_code, 302)
        from transactions.models import Transaction
        txn = Transaction.objects.filter(user=self.user, type='deposit').first()
        self.assertIsNotNone(txn)
        self.assertEqual(txn.status, 'pending')
        self.user.refresh_from_db()
        self.assertEqual(self.user.balance, before)  # not credited until admin approves

    def test_dashboard_and_kyc_pages_render(self):
        self.client.force_login(self.user)
        for path in [reverse('dashboard:index'), reverse('dashboard:kyc'), reverse('dashboard:deposits')]:
            self.assertEqual(self.client.get(path).status_code, 200)


@_TEST_STATIC
class TradesPageTests(TestCase):
    def setUp(self):
        from copytrading.models import MasterTrader, MasterTrade, CopyRelationship
        self.MasterTrade = MasterTrade
        self.CopyRelationship = CopyRelationship
        self.user = User.objects.create_user('tp', 'tp@example.com', 'pw')
        self.master = MasterTrader.objects.create(name='Pro Trader', slug='pro-trader',
                                                  headline='x', strategy='x', win_rate=60, return_pct=10)
        self.t_verified = MasterTrade.objects.create(
            master=self.master, crypto_currency='Bitcoin', crypto_symbol='BTC/USD',
            amount='100', direction='rise', result='win', status='closed', is_verified=True)
        self.t_pending = MasterTrade.objects.create(
            master=self.master, crypto_currency='Gold', crypto_symbol='XAU/USD',
            amount='50', direction='fall', result='pending', status='open', is_verified=False)
        self.url = reverse('dashboard:trades')

    def test_non_copier_sees_empty(self):
        self.client.force_login(self.user)
        r = self.client.get(self.url)
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "not copying any traders")
        self.assertNotContains(r, 'BTC/USD')

    def test_copier_sees_all_master_trades_incl_pending(self):
        self.CopyRelationship.objects.create(user=self.user, master=self.master,
                                             allocated_demo_amount='1000', is_active=True)
        self.client.force_login(self.user)
        r = self.client.get(self.url)
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, 'BTC/USD')          # verified trade shown
        self.assertContains(r, 'XAU/USD')          # unverified trade also shown
        self.assertContains(r, 'Pending review')   # flagged

    def test_search_filters(self):
        self.CopyRelationship.objects.create(user=self.user, master=self.master,
                                             allocated_demo_amount='1000', is_active=True)
        self.client.force_login(self.user)
        r = self.client.get(self.url, {'q': 'BTC'})
        self.assertContains(r, 'BTC/USD')
        self.assertNotContains(r, 'XAU/USD')


@_TEST_STATIC
class AdminFinancialMathTests(TestCase):
    """Admin profit/bonus/referral edits adjust balance, log a transaction, sync trading account."""
    def setUp(self):
        from decimal import Decimal
        self.Decimal = Decimal
        self.admin = User.objects.create_superuser('fa', 'fa@e.com', 'pw')
        self.user = User.objects.create_user('fu', 'fu@e.com', 'pw')
        self.user.balance = Decimal('1000.00'); self.user.total_profit = Decimal('0.00')
        self.user.save()

    def _save_via_admin(self, changed_data=None):
        from django.contrib import admin as dj_admin
        from django.test import RequestFactory
        from django.contrib.messages.storage.fallback import FallbackStorage
        ma = dj_admin.site._registry[User]
        req = RequestFactory().post('/admin/accounts/user/x/change/')
        req.user = self.admin
        setattr(req, 'session', {}); setattr(req, '_messages', FallbackStorage(req))
        class _Form:
            pass
        f = _Form(); f.changed_data = changed_data or []
        ma.save_model(req, self.user, f, change=True)

    def test_profit_increase_bumps_balance_and_logs(self):
        from transactions.models import Transaction
        from trading.models import TradingAccount
        self.user.total_profit = self.Decimal('500.00')   # +500 vs DB (0)
        self._save_via_admin(changed_data=['total_profit'])
        self.user.refresh_from_db()
        self.assertEqual(self.user.balance, self.Decimal('1500.00'))   # 1000 + 500
        txn = Transaction.objects.filter(user=self.user, type='profit').first()
        self.assertIsNotNone(txn)
        self.assertEqual(txn.amount, self.Decimal('500.00'))
        self.assertEqual(txn.status, 'approved')
        ta = TradingAccount.objects.get(user=self.user)
        self.assertEqual(ta.trading_balance, self.Decimal('1500.00'))  # synced
        self.assertEqual(ta.equity, self.Decimal('1500.00'))

    def test_direct_balance_edit_not_double_counted(self):
        self.user.balance = self.Decimal('2000.00')
        self.user.total_bonus = self.Decimal('100.00')   # also changed bonus
        self._save_via_admin(changed_data=['balance', 'total_bonus'])
        self.user.refresh_from_db()
        # balance respected as typed (not 2000+100)
        self.assertEqual(self.user.balance, self.Decimal('2000.00'))

    def test_profit_decrease_debits_balance(self):
        self.user.total_profit = self.Decimal('300.00'); self.user.save()
        self.user.total_profit = self.Decimal('100.00')  # -200
        self._save_via_admin(changed_data=['total_profit'])
        self.user.refresh_from_db()
        self.assertEqual(self.user.balance, self.Decimal('800.00'))   # 1000 - 200


@_TEST_STATIC
class TwoFactorTests(TestCase):
    def setUp(self):
        from unittest import mock
        p = mock.patch('accounts.email_utils.EmailService.send_email', return_value=True)
        p.start(); self.addCleanup(p.stop)
        self.user = User.objects.create_user('tfa', 'tfa@example.com', 'Secret123!')

    def test_toggle_enables_and_disables(self):
        self.client.force_login(self.user)
        self.client.post(reverse('dashboard:toggle_two_factor'))
        self.user.refresh_from_db(); self.assertTrue(self.user.two_factor_enabled)
        self.client.post(reverse('dashboard:toggle_two_factor'))
        self.user.refresh_from_db(); self.assertFalse(self.user.two_factor_enabled)

    def test_login_without_2fa_logs_in_directly(self):
        r = self.client.post(reverse('accounts:login'), {'username': 'tfa', 'password': 'Secret123!'})
        self.assertEqual(r.status_code, 302)
        self.assertIn('_auth_user_id', self.client.session)

    def test_login_with_2fa_requires_code(self):
        from accounts.models import LoginCode
        self.user.two_factor_enabled = True; self.user.save()
        r = self.client.post(reverse('accounts:login'), {'username': 'tfa', 'password': 'Secret123!'})
        self.assertEqual(r.status_code, 302)
        self.assertIn(reverse('accounts:two_factor_verify'), r.url)
        self.assertNotIn('_auth_user_id', self.client.session)   # NOT logged in yet
        self.assertEqual(self.client.session.get('2fa_user_id'), self.user.id)
        code = LoginCode.objects.filter(user=self.user).latest('created_at').code
        # wrong code rejected
        self.client.post(reverse('accounts:two_factor_verify'), {'code': '000000'})
        self.assertNotIn('_auth_user_id', self.client.session)
        # correct code logs in
        r2 = self.client.post(reverse('accounts:two_factor_verify'), {'code': code})
        self.assertEqual(r2.status_code, 302)
        self.assertIn('_auth_user_id', self.client.session)

    def test_2fa_verify_without_pending_session_redirects(self):
        r = self.client.get(reverse('accounts:two_factor_verify'))
        self.assertEqual(r.status_code, 302)
        self.assertIn(reverse('accounts:login'), r.url)
