# Generated by Django 4.2.7 on 2025-10-31 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('bonus', 'Bonus'), ('referral', 'Referral Bonus'), ('profit', 'Profit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('usdt', 'USDT (TRC20)'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Credit/Debit Card')], max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID or reference', max_length=255)),
                ('payment_address', models.CharField(blank=True, help_text='Wallet address or account number', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True, help_text='Internal notes for administrators')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_address', models.CharField(help_text='Wallet address or account details', max_length=255)),
                ('withdrawal_method', models.CharField(max_length=50)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_details', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-transaction__created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='deposits/')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_details', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-transaction__created_at'],
            },
        ),
    ]
