# Generated by Django 4.2.7 on 2026-06-19 13:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Label for this beneficiary', max_length=100)),
                ('type', models.CharField(choices=[('local_bank', 'Local Bank'), ('wire', 'International Wire'), ('crypto', 'Cryptocurrency'), ('paypal', 'PayPal'), ('wise', 'Wise'), ('cashapp', 'Cash App'), ('other', 'Other')], default='local_bank', max_length=20)),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Method-specific details (email, tag, wallet, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., USDT, Bitcoin, Ethereum', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit Only'), ('withdrawal', 'Withdrawal Only'), ('both', 'Both')], default='both', max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payment_methods/')),
                ('min_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=15)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for no limit', max_digits=15, null=True)),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount or percentage based on charge type', max_digits=10)),
                ('duration', models.CharField(blank=True, help_text="e.g., '1-24 hours', 'Instant'", max_length=100)),
                ('wallet_address', models.CharField(blank=True, help_text='Platform wallet address for receiving payments', max_length=200)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SwapRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_usd_price', models.DecimalField(decimal_places=2, default=Decimal('65000.00'), help_text='Price of 1 BTC in USD', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Swap Rate',
                'verbose_name_plural': 'Swap Rate',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('bonus', 'Bonus'), ('referral', 'Referral Bonus'), ('profit', 'Profit'), ('swap', 'Currency Swap'), ('loan', 'Loan Disbursement'), ('grant', 'Grant Disbursement')], max_length=20),
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('usd_to_btc', 'USD to BTC'), ('btc_to_usd', 'BTC to USD')], max_length=20)),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rate_used', models.DecimalField(decimal_places=2, help_text='BTC/USD price applied', max_digits=15)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Swap',
                'verbose_name_plural': 'Swaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('local', 'Local Transfer'), ('international', 'International Transfer')], max_length=20)),
                ('method', models.CharField(choices=[('local_bank', 'Local Bank'), ('wire', 'Wire Transfer'), ('crypto', 'Cryptocurrency'), ('paypal', 'PayPal'), ('wise', 'Wise'), ('cashapp', 'Cash App'), ('other', 'Other')], default='local_bank', max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='transactions.beneficiary')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_transfer', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'External Transfer',
                'verbose_name_plural': 'External Transfers',
                'ordering': ['-transaction__created_at'],
            },
        ),
    ]
