# Generated by Django 4.2.7 on 2026-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_beneficiary_paymentmethod_swaprate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('bonus', 'Bonus'), ('referral', 'Referral Bonus'), ('profit', 'Profit'), ('swap', 'Currency Swap')], max_length=20),
        ),
    ]
