# Generated by Django 4.2.7 on 2026-07-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawals_enabled', models.BooleanField(default=True, help_text="When OFF, the 'Request code' and 'Complete Request' buttons are hidden on the withdrawal page and withdrawal requests are blocked. Use during maintenance or when you're having trouble processing withdrawals.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
