# Generated by Django 4.2.7 on 2026-08-08 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0005_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('label', models.CharField(blank=True, help_text="Your own note — e.g. 'Acme Ltd — mandate of 12 Aug 2026'. Not shown to the user.", max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to revoke the code immediately without deleting the record.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank and the code never expires.', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses. Set to 1 to make it single-use.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_withdrawal_codes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The account this code authorises withdrawals for.', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_access_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Access Code',
                'verbose_name_plural': 'Withdrawal Access Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
