# Generated by Django 4.2.7 on 2026-08-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_withdrawalaccesscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalaccesscode',
            name='code',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
