# Generated by Django 4.2.7 on 2026-08-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_withdrawalaccesscode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='request_code_enabled',
            field=models.BooleanField(default=True, help_text="When OFF, users can no longer email themselves a one-time code — the 'Request code' button disappears and only admin-issued Withdrawal Access Codes are accepted. Leave ON unless you want every withdrawal to go through a code you issued yourself.", verbose_name='"Request code" button enabled'),
        ),
    ]
